# Prometheus configuration for Virtual Game Web App

global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Alerting rules
rule_files:
  - "alert_rules.yml"

# Scrape configurations
scrape_configs:
  # Spring Boot application metrics
  - job_name: 'virtual-game-app'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['app:8080']

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']

  # PostgreSQL metrics (using postgres-exporter)
  - job_name: 'postgres'
    scrape_interval: 10s
    static_configs:
      - targets: ['postgres-exporter:9187']

  # Redis metrics (using redis-exporter)
  - job_name: 'redis'
    scrape_interval: 10s
    static_configs:
      - targets: ['redis-exporter:9121']

  # Kafka metrics (using JMX exporter)
  - job_name: 'kafka'
    scrape_interval: 10s
    static_configs:
      - targets: ['kafka:9308']
